---
Web:
  port: 5000

Client:
  appName: raspinodemon

RPC:
  host: 10.10.10.3
  port: 8332
  rpc_username: bitcoinrpc
  rpc_password: djdjeei38384itmymykgg8f9rororkrkmrkrofofoeoe9woeidjdjekeoekdmd
  
Api:
  restCalls:
    - callName: getinfo
      inputName: none
      inputType: none
      uri: '/getinfo'
    - callName: getpeerinfo
      inputName: none
      inputType: none
      uri: '/getpeerinfo'
      timeout: 4000
    - callName: getnetworkinfo
      inputName: none
      inputType: none
      uri: '/getnetworkinfo'
    - callName: getmempoolinfo
      inputName: none
      inputType: none
      uri: '/getmempoolinfo'
    - callName: getrawmempool
      inputName: none
      inputType: none
      uri: '/getrawmempool'
      timeout: 4000
    - callName: getmempoolentry
      inputName: hash
      inputType: string
      uri: '/getmempoolentry/:hash'
    - callName: getblockhash
      inputName: index
      inputType: number
      uri: '/getblockhash/:index'
    - callName: getblock
      inputName: hash
      inputType: string
      uri: '/getblock/:hash'
    - callName: estimatefee
      inputName: nblocks
      inputType: number
      uri: '/estimatefee/:nblocks'
    - callName: getrawtransaction
      inputName: txid
      inputType: string
      uri: '/getrawtransaction/:txid'
      verbose: true
...
